aws_access_key_id=AKIAY6HM2ZTJL27IJAFG
aws_secret_access_key=okjkljdfhdhakljasklgjlkglkjlcaikasjgklsdjgkis7O8skljkljlkjklxzfz+y35FGry9+hqvtUuFGb2aD
#aws_secret_access_key=ocasK+uf7OPF8sxzfz+y35FGry9+hqvtUuFGb2aD
